### ISSUE TITLE
List input for social media links

### ISSUE THREAD

**Issue by gytdau** [gytdau/identi.fyi#13]
Right now, we have a system where there's a field for Facebook, LinkedIn, etc.

We could make it easier: just paste your links into a list, and the system autodetects the social media site it links to using something like regex.

**Comment by coisin** [comment]
I'll get working on that tonight.

**Comment by gytdau** [comment]
I'm not sure if simple keyword matching will work in edge cases.

http://www.facebook.com/bla-bla-twitter-group

would match for both Twitter and Facebook, depending on what site comes first.

Or:

http://www.myblog.com/posts/how-twitter-ruins-your-life

Would actually match for Twitter.

**Comment by coisin** [comment]
I checked and they do work
